### ISSUE TITLE
`get_feature_names_out` for encoders

### ISSUE THREAD

**Issue by CarloLepelaars** [koaning/embetter#29]
I would be happy to implement `get_feature_names_out` for all the Embetter objects. I will implement them by just adding a new method (without a Mixin).

**Comment by koaning** [comment]
I might want to put that on hold for a bit, partially because I don't have a super clear roadmap in what I do/not want to cover in this library. Maybe I want to have sparse embeddings, or 2d/3d embeddings as well? In which case I might have tools that are a bit of an anti-pattern. 

Maybe later, but at this point the project needs to mature before I consider such features.
